apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCh4iJ9lGggXn5aOQWNMj3js/DPzCXiAbN8iANMIHvwgISa1yhldCFSHp2ODMgl884Rhcg2+/GngSJrAUSm0fa8JSVDHWEfrcz3WFa/0r0RqqZgSoT6/FUaxixDl7NndDZhzTbppNiLpIvCzm7/JgkLp04PyLtU70z4pOMZAPnPzEMo+AcXpQcyVOLfGTuzlfaYn0unuVkWinBiiclrB5tnmcjY7I7wqigtTt38ps4tIl4OT6Ql0oGDi0+4F+fHElVrkrElNHyz1WTj+5SwXc8M990mYKKP3639o8ynYpBeMSnX039MsQiYzoF9Jhc6+JCelMGK1xLIFIZAMUk3VuC+KkmNcMCCoEMaB5Nk7xOFh917/PYLyHlYShKFSAGYeBjyrXvU0Y9dmN9ymIskKo4Zu/Gi+jz2IiQqdvScAm2LlW1T6Mmn6KKz3n2jL++oV/YAPaUGWMkwIRqeSHbBWRp7fKFawdz3H0k795AQWzdHXFTIKa1au2JO79w08MGL/McJVROAYkmKEihyl+mBxGCYefXFxs14xeSsoU4iz2ORp9T2vgCcEGeHaYTSH1U6CcXb4e4fJyNQdXSVht4wpckdZHc92WzmxOfvjplBsg/HeUiAiweYgyeCRsfzgdgfZF+mAPyhyf5OaZWh4k5AHKIib0dIEMkaXDk/gh4uJ9nfKJ7xMuJ0AkAQXtYm9AwEO3T2Ydr2mBpYBYEarIepQTRPQ3TBFGJpxmiLa6EIJWXzbuREJ2ftmllU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

